# Command to be used in the terminal, for testing purposes

# xcodebuild clean build test \
#     -workspace CEPApp/CEPApp.xcworkspace/ \
#     -scheme "CEPApp" \
#     -sdk iphonesimulator \
#     -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
#     -testPlan "CI-iOS" \
#     CODE_SIGN_IDENTITY="" \
#     CODE_SIGNING_REQUIRED=NO \
#     ONLY_ACTIVE_ARCH=YES

name: CI-iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test iOS CI
      run: xcodebuild clean build test -workspace CEPApp/CEPApp.xcworkspace/ -scheme "CEPApp" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" -testPlan "CI-iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES