name: CI-macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test MacOS CI
      run: xcodebuild clean build test -project CEPSearch/CEPSearch.xcodeproj/ -scheme "CEPSearch" -sdk macosx14.2 -destination "platform=macOS,arch=arm64" -testPlan "CI-macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
